name: modbook
recipe: drupal10
config:
  webroot: web
  composer: 2.8
  php: 8.3
services:
  node:
    type: node:22
tooling:
  npm:
    service: node
  node:
    service: node
  npx:
    service: node
  yarn:
    service: node
